--- # Bootstrap Webservers
- hosts: webservers
  become: yes
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: latest
  - name: create index.html file
    file:
      name: /var/www/html/index.html
      state: touch
  - name: add web content
    lineinfile:
<<<<<<< HEAD
      line: "this is ansible file on integration branch"
>>>>>>> release
      path: /var/www/html/index.html
  - name: start apache2
    service:
      name: apache2
      state: started
<<<<<<< HEAD



=======
>>>>>>> release

